
stages:
  - test

# Test Stage
test:
  stage: test
  image: python:3.12
  script:
    - make environment  # Configure virtual environment
    - make test  # Run tests
  only:
    - main
    - merge_requests