stages:
  - test
  - coverage
  - lint
  - static-analysis

variables:
  COVERAGE_OPTIONS: "--cov-config=.coveragerc --cov=src src/tests/ --cov-report=xml --cov-report=term-missing"
  BANDIT_OPTIONS: "-r src/ -c .bandit.yml --exclude src/tests,src/core/config.py"

default:
  image: python:3.12

# Test Stage
test:
  stage: test
  script:
    - make environment
    - pytest $COVERAGE_OPTIONS
  artifacts:
    paths:
      - coverage.xml  # Pass coverage data to the next stage
    expire_in: 1 week

# Coverage Stage
coverage:
  stage: coverage
  script:
    - make environment
    - pytest $COVERAGE_OPTIONS
    - coverage html  # Generate an HTML report for better visualization
  artifacts:
    paths:
      - htmlcov/      # Store the HTML coverage report directory
    expire_in: 1 week
  needs:
    - test
  

# Linting Stage
lint:
  stage: lint
  script:
    - make environment
    - pylint src/

# Static Analysis Stage
static-analysis:
  stage: static-analysis
  script:
    - make environment
    - bandit $BANDIT_OPTIONS
