
stages:
  - test
  - lint
  - static-analysis

# Test Stage
test:
  stage: test
  image: python:3.12
  script:
    - make environment
    - pytest --cov=src --cov-report=xml --cov-report=term-missing
  artifacts:
    paths:
      - coverage.xml
    expire_in: 1 week

# Étape de linting
lint:
  stage: lint
  image: python:3.12
  script:
    - make environment
    - pylint src/

# Étape d'analyse statique
static-analysis:
  stage: static-analysis
  image: python:3.12
  script:
    - make environment
    - bandit -r src/